import type { Metadata } from "next";
import "./globals.css";
import SideNav from "@/components/SideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen md:flex-row md:overflow-hidden">
          <SideNav />
          <main className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</main>
        </div>
      </body>
    </html>
  );
}
