import type { Metadata } from "next";
import "@/app/globals.css"
import { inter } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Ritmo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
